print ("My Name is Nasir Sharif")
print ("Today is my first day in my class in Navttc Python Course")
print ("This is my first program of Advanced Python")
print("I am sure to learn a lot of foundational things in this course")
print(":/")
